#!/usr/bin/with-contenv bash
# Fix BOSH proxy configuration after meet.conf is generated
# This script runs automatically on container startup (after 10-config generates meet.conf)
# Scripts in /config/ are executed in numerical order (10-config runs before 99-fix-bosh.sh)

MEET_CONF="/config/nginx/meet.conf"
FIXED_TEMPLATE="/config/nginx/meet.conf.fixed"

echo "[BOSH Fix Script] Starting BOSH configuration fix..."

# Wait for meet.conf to be generated by 10-config script
echo "[BOSH Fix Script] Waiting for meet.conf to be generated..."
for i in {1..30}; do
    if [ -f "$MEET_CONF" ]; then
        echo "[BOSH Fix Script] meet.conf found"
        break
    fi
    sleep 1
done

if [ ! -f "$MEET_CONF" ]; then
    echo "[BOSH Fix Script] ERROR: meet.conf not found after 30 seconds"
    exit 1
fi

echo "[BOSH Fix Script] Fixing BOSH configuration..."

# Create backup
cp "$MEET_CONF" "${MEET_CONF}.backup.$(date +%s)" 2>/dev/null || true

# Method 1: Use sed to replace incorrect BOSH configurations
# Replace incorrect proxy_pass patterns
sed -i 's|proxy_pass http://localhost/http-bind/http-bind;|proxy_pass http://prosody:5280/http-bind;|g' "$MEET_CONF"
sed -i 's|proxy_pass http://localhost:5280/http-bind;|proxy_pass http://prosody:5280/http-bind;|g' "$MEET_CONF"
sed -i 's|proxy_set_header Host localhost;|proxy_set_header Host $http_host;|g' "$MEET_CONF"
# Fix Host header if it's set to a specific IP address (should use variable)
sed -i 's|proxy_set_header Host [0-9.]*;|proxy_set_header Host $http_host;|g' "$MEET_CONF"

# Method 2: Use perl to replace entire BOSH location blocks (more reliable)
if command -v perl >/dev/null 2>&1; then
    # Replace main BOSH location block with correct configuration
    perl -i -0pe 's/location = \/http-bind \{.*?proxy_pass[^;]*;.*?\n\}/# BOSH - Fixed to use prosody service\nlocation = \/http-bind {\n    proxy_set_header X-Forwarded-For \$remote_addr;\n    proxy_set_header Host \$http_host;\n    proxy_set_header X-Forwarded-Proto \$scheme;\n\n    proxy_pass http:\/\/prosody:5280\/http-bind;\n    proxy_buffering off;\n    tcp_nodelay on;\n    proxy_read_timeout 3600s;\n    proxy_http_version 1.1;\n    proxy_pass_request_headers on;\n    proxy_pass_request_body on;\n}\n/gs' "$MEET_CONF"
    
    # Replace subdomain BOSH location blocks that use rewrite
    perl -i -0pe 's/location ~ \^\/\(\[^\/\?&:''""\]\+\)\/http-bind \{.*?rewrite[^}]*\}/# BOSH for subdomains - Fixed to proxy directly to prosody\n    location ~ ^\/([^\/\?&:''""]+)\/http-bind {\n        proxy_set_header X-Forwarded-For \$remote_addr;\n        proxy_set_header Host \$http_host;\n        proxy_set_header X-Forwarded-Proto \$scheme;\n        \n        proxy_pass http:\/\/prosody:5280\/http-bind;\n        proxy_buffering off;\n        tcp_nodelay on;\n        proxy_read_timeout 3600s;\n        proxy_http_version 1.1;\n        proxy_pass_request_headers on;\n        proxy_pass_request_body on;\n    }/gs' "$MEET_CONF"
fi

# Method 3: If fixed template exists and main BOSH block is still wrong, use template
if [ -f "$FIXED_TEMPLATE" ]; then
    if ! grep -q "proxy_pass http://prosody:5280/http-bind;" "$MEET_CONF"; then
        echo "[BOSH Fix Script] Using fixed template..."
        # Extract just the BOSH sections from template and inject into generated config
        # This is safer than replacing entire file
        grep -A 10 "location = /http-bind" "$FIXED_TEMPLATE" > /tmp/bosh_main.txt 2>/dev/null || true
        grep -A 10 "location ~.*http-bind" "$FIXED_TEMPLATE" > /tmp/bosh_subdomain.txt 2>/dev/null || true
    fi
fi

# Method 4: Ensure main BOSH location block exists with correct config
if ! grep -q "proxy_pass http://prosody:5280/http-bind;" "$MEET_CONF"; then
    echo "[BOSH Fix Script] Adding correct BOSH location block..."
    
    # Find insertion point (after static content, before colibri)
    STATIC_LINE=$(grep -n '# ensure all static content' "$MEET_CONF" | tail -1 | cut -d: -f1)
    if [ -n "$STATIC_LINE" ]; then
        # Find the closing brace of static content location
        INSERT_LINE=$(awk "NR > $STATIC_LINE && /^}/ {print NR; exit}" "$MEET_CONF")
        if [ -z "$INSERT_LINE" ]; then
            INSERT_LINE=$((STATIC_LINE + 12))
        fi
        
        sed -i "${INSERT_LINE}a\\
\\
# BOSH - Fixed to use prosody service\\
location = /http-bind {\\
    proxy_set_header X-Forwarded-For \$remote_addr;\\
    proxy_set_header Host \$http_host;\\
    proxy_set_header X-Forwarded-Proto \$scheme;\\
\\
    proxy_pass http://prosody:5280/http-bind;\\
    proxy_buffering off;\\
    tcp_nodelay on;\\
    proxy_read_timeout 3600s;\\
    proxy_http_version 1.1;\\
    proxy_pass_request_headers on;\\
    proxy_pass_request_body on;\\
}\\
" "$MEET_CONF"
    fi
fi

# Verify the fix
if grep -q "proxy_pass http://prosody:5280/http-bind;" "$MEET_CONF"; then
    echo "[BOSH Fix Script] ✅ Configuration fixed successfully"
    
    # Test nginx configuration
    if nginx -t >/dev/null 2>&1; then
        echo "[BOSH Fix Script] ✅ Nginx configuration test passed"
    else
        echo "[BOSH Fix Script] ⚠️  WARNING: Nginx configuration test failed"
        nginx -t 2>&1 | head -5
    fi
else
    echo "[BOSH Fix Script] ❌ ERROR: Fix verification failed - prosody proxy_pass not found"
    exit 1
fi

# Remove all malformed BOSH blocks (including single-line ones)
sed -i '/# BOSH.*location = \/http-bind.*{.*}/d' "$MEET_CONF"
sed -i '/location = \/http-bind.*{.*proxy_pass.*}/d' "$MEET_CONF"
# Fix empty proxy_set_header values
sed -i 's|proxy_set_header X-Forwarded-For ;|proxy_set_header X-Forwarded-For $remote_addr;|g' "$MEET_CONF"
sed -i 's|proxy_set_header Host ;|proxy_set_header Host $http_host;|g' "$MEET_CONF"
sed -i 's|proxy_set_header X-Forwarded-Proto ;|proxy_set_header X-Forwarded-Proto $scheme;|g' "$MEET_CONF"
# Remove proxy_method POST (not supported in some nginx versions)
sed -i '/proxy_method POST;/d' "$MEET_CONF"

# Fix meeting room routing to serve index.html
echo "[BOSH Fix Script] Fixing meeting room routing..."

# Remove any @root_path location block first
sed -i '/location @root_path {/,/^}/d' "$MEET_CONF"
# Remove any references to @root_path
sed -i '/@root_path/d' "$MEET_CONF"

# Fix try_files directive to serve index.html directly
sed -i 's|try_files $uri @root_path;|try_files $uri $uri/ /index.html;|g' "$MEET_CONF"
sed -i 's|try_files $uri;|try_files $uri $uri/ /index.html;|g' "$MEET_CONF"

# Replace meeting room location block with proper configuration
# Use sed instead of perl to avoid escaping issues
# Remove old meeting room location block
sed -i '/location ~ \^\/\(\[^\/\?&:'"'"'"]\+\)\$/,/^}/d' "$MEET_CONF"
sed -i '/location ~.*\[^\/\?&:'"'"'"]\+.*\$/,/^}/d' "$MEET_CONF"

# Find insertion point (after colibri websockets)
MEETING_LINE=$(grep -n '# colibri (JVB) websockets' "$MEET_CONF" | head -1 | cut -d: -f1)
if [ -n "$MEETING_LINE" ]; then
    # Find the line after the colibri location block ends (find closing brace)
    AFTER_COLIBRI=$(awk "NR > $MEETING_LINE && /^}/ {print NR+1; exit}" "$MEET_CONF")
    if [ -z "$AFTER_COLIBRI" ]; then
        # If can't find closing brace, insert after a few lines
        AFTER_COLIBRI=$((MEETING_LINE + 10))
    fi
    # Insert the meeting room routing block
    sed -i "${AFTER_COLIBRI}i\\
\\
# Meeting room routing - serve index.html\\
location ~ ^/([^/?&:'"'"'"]+)$ {\\
    try_files \$uri \$uri/ /index.html;\\
}\\
" "$MEET_CONF"
else
    # If colibri section not found, append at end
    echo "" >> "$MEET_CONF"
    echo "# Meeting room routing - serve index.html" >> "$MEET_CONF"
    echo "location ~ ^/([^/?&:'"'"'"]+)$ {" >> "$MEET_CONF"
    echo "    try_files \$uri \$uri/ /index.html;" >> "$MEET_CONF"
    echo "}" >> "$MEET_CONF"
fi

# Ensure root is set correctly
if ! grep -q "^root /usr/share/jitsi-meet;" "$MEET_CONF"; then
    sed -i '/^server_name/a\
root /usr/share/jitsi-meet;' "$MEET_CONF"
fi

# Final nginx test and reload after all fixes
echo "[BOSH Fix Script] Final nginx configuration test..."
if nginx -t 2>&1; then
    nginx -s reload 2>&1 || echo "[BOSH Fix Script] ⚠️  Warning: nginx reload failed, but config test passed"
    echo "[BOSH Fix Script] ✅ Meeting room routing fixed and nginx reloaded"
    
    # Verify meeting room location block
    if grep -q "location ~ ^/(\[^/\]\+)$" "$MEET_CONF" && grep -q "try_files.*/index.html" "$MEET_CONF"; then
        echo "[BOSH Fix Script] ✅ Meeting room routing verified"
    else
        echo "[BOSH Fix Script] ⚠️  Warning: Meeting room routing may not be properly configured"
        echo "[BOSH Fix Script] Current meeting room block:"
        grep -n -A 3 "location ~ ^/(\[^/\]\+)$" "$MEET_CONF" | head -5
    fi
else
    echo "[BOSH Fix Script] ❌ ERROR: nginx configuration test failed after fixes"
    echo "[BOSH Fix Script] Error details:"
    nginx -t 2>&1 | head -20
    exit 1
fi

echo "[BOSH Fix Script] ✅ BOSH configuration fix completed successfully"
