
videobridge {
    ice {
        udp {
            port = 10000
        }
    }
    apis {
        xmpp-client {
            configs {

                shard0 {
                    HOSTNAME = "prosody"
                    PORT = "5222"
                    DOMAIN = "auth.localhost"
                    USERNAME = "jvb"
                    PASSWORD = "0d6aecf3cf9ab3d45361f7bc7f2ddfc9"
                    MUC_JIDS = "jvbbrewery@internal-muc.localhost"
                    MUC_NICKNAME = "1f2aad191472"
                    DISABLE_CERTIFICATE_VERIFICATION = true
                }
}
        }
        rest {
            enabled = false
        }
    }
    rest {
        shutdown {
            enabled = false
        }
    }
    stats {
        enabled = true
    }
    websockets {
        enabled = true
        domain = "localhost:8443"
        tls = true
        server-id = "172.18.0.4"
    }
    multi-stream {
        enabled = false
    }
    http-servers {
        private {
          host = 0.0.0.0
        }
        public {
            host = 0.0.0.0
            port = 9090
        }
    }

    }

ice4j {
    harvest {
        mapping {
            stun {
addresses = [ "stun.l.google.com:19302","stun1.l.google.com:19302" ]
}
            static-mappings = [
{
                    local-address = "172.18.0.4"
                    public-address = "localhost"
                }
]
        }
    }
}
